### ISSUE TITLE
Call other Command from Command

### ISSUE THREAD

**Issue by julianpaulozzi** [poxet/tharga-console#4]
Some form of call another command within the active command?
Or set the next command in front of ">"?

**Comment by poxet** [comment]
I am not sure what you mean. Do you have an example?

**Comment by julianpaulozzi** [comment]
I have utility command serving as a "parameters builder" for a more complex command (on RootCommand).
Soon after 'build' would expose the command to run directly.

**Comment by poxet** [comment]
If I understand this correctly, you want the output of one command to be the input of another command.

For now, there is a workaround for this. I added an example named *ParametersCommand* where you can execute *param build* to build parameters and *param execute* that uses the same way of building parameters.

What it does is to have a method exposed (CreateParameters) that can be used by several commands.

This can also be used if you have commands that overlap and you do not want to have duplicate code.

Please get back to me if this soles you problem, and if not. A suggestion on how it should work would be great.
