### ISSUE TITLE
command from start of console nerver excute

### ISSUE THREAD

**Issue by windwp** [poxet/tharga-console#5]
My sub command "app1" don't run in start when I excute it from dos 
Example:
C:\Users\longt>myconsole.exe runapp app1

**Comment by windwp** [comment]
I just found change this in Program.cs and sub command will excute
```csharp
 var commandEngine = new CommandEngine(command);
 commandEngine.Run(new[] { string.Join(" ", args) });
```

**Comment by poxet** [comment]
This should work too.

```csharp
var commandEngine = new CommandEngine(command);
commandEngine.Run(args);
```

Do you have to do "new[] { string.Join(" ", args) }", or it does not work?

**Comment by windwp** [comment]
Sorry my mistake, I forget to add quote in subcommand :)
C:\Users\longt>myconsole.exe "runapp app1"
